"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fleet_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_vehicles', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('simulated','uploaded')", name='ck_dataset_source'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=False),
    sa.Column('battery_chemistry', sa.String(length=3), nullable=False),
    sa.Column('cooling_type', sa.String(length=10), nullable=False),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('ac_charge_power_kw', sa.Float(), nullable=False),
    sa.Column('dc_charge_power_kw', sa.Float(), nullable=False),
    sa.Column('energy_use_wh_km', sa.Float(), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=False),
    sa.Column('distance_per_year_km', sa.Float(), nullable=False),
    sa.Column('vehicle_age_years', sa.Float(), nullable=False),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=False),
    sa.Column('dc_fast_pct', sa.Float(), nullable=False),
    sa.Column('daily_charge_limit', sa.Float(), nullable=False),
    sa.Column('min_soc', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("battery_chemistry IN ('LFP','NMC','NCA','LTO')", name='ck_vehicles_chem'),
    sa.CheckConstraint("cooling_type IN ('liquid','air','passive')", name='ck_vehicles_cooling'),
    sa.CheckConstraint('battery_capacity_kwh > 0', name='ck_vehicles_cap_pos'),
    sa.CheckConstraint('daily_charge_limit BETWEEN 50 AND 100 AND min_soc BETWEEN 0 AND 60 AND dc_fast_pct BETWEEN 0 AND 100', name='ck_vehicles_soc_ranges'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('battery_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('measured_soh', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('cell_temperature', sa.Float(), nullable=True),
    sa.Column('soc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('measured_soh BETWEEN 0 AND 100', name='ck_meas_soh'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meas_vehicle_time', 'battery_measurements', ['vehicle_id', 'measured_at'], unique=False)
    op.create_table('charging_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('charging_type', sa.String(length=2), nullable=False),
    sa.Column('charging_power_kw', sa.Float(), nullable=False),
    sa.Column('start_soc', sa.Float(), nullable=False),
    sa.Column('end_soc', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('charging_duration_min', sa.Float(), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("charging_type IN ('AC','DC')", name='ck_charge_type'),
    sa.CheckConstraint('start_soc BETWEEN 0 AND 100 AND end_soc BETWEEN 0 AND 100', name='ck_charge_soc'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_charge_vehicle_time', 'charging_history', ['vehicle_id', 'charged_at'], unique=False)
    op.create_table('fleet_training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_ref', sa.String(length=64), nullable=False),
    sa.Column('chem', sa.String(length=3), nullable=False),
    sa.Column('cooling', sa.Integer(), nullable=False),
    sa.Column('cap_kwh', sa.Float(), nullable=False),
    sa.Column('ac_kw', sa.Float(), nullable=False),
    sa.Column('dc_kw', sa.Float(), nullable=False),
    sa.Column('whkm', sa.Float(), nullable=False),
    sa.Column('age_yr', sa.Float(), nullable=False),
    sa.Column('odo_km', sa.Float(), nullable=False),
    sa.Column('km_per_yr', sa.Float(), nullable=False),
    sa.Column('tamb_c', sa.Float(), nullable=False),
    sa.Column('fast_pct', sa.Float(), nullable=False),
    sa.Column('charge_limit', sa.Float(), nullable=False),
    sa.Column('min_soc', sa.Float(), nullable=False),
    sa.Column('soh_pct', sa.Float(), nullable=False),
    sa.CheckConstraint("chem IN ('LFP','NMC','NCA','LTO')", name='ck_fleet_chem'),
    sa.CheckConstraint('cooling BETWEEN 1 AND 3', name='ck_fleet_cooling'),
    sa.ForeignKeyConstraint(['dataset_id'], ['fleet_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fleet_dataset_vehicle', 'fleet_training_data', ['dataset_id', 'vehicle_ref'], unique=False)
    op.create_index(op.f('ix_fleet_training_data_dataset_id'), 'fleet_training_data', ['dataset_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('n_test', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_importance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fleet_datasets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_dataset_id'), 'ml_models', ['dataset_id'], unique=False)
    op.create_index('uq_ml_models_one_active', 'ml_models', ['is_active'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.create_table('soh_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('soh_source', sa.String(length=12), nullable=False),
    sa.Column('physics_soh', sa.Float(), nullable=False),
    sa.Column('ml_correction', sa.Float(), nullable=True),
    sa.Column('hybrid_soh', sa.Float(), nullable=False),
    sa.Column('anchor_scale', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('life_remaining_years', sa.Float(), nullable=False),
    sa.Column('life_optimized_years', sa.Float(), nullable=False),
    sa.Column('life_gained_years', sa.Float(), nullable=False),
    sa.Column('efc', sa.Float(), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW','MODERATE','HIGH')", name='ck_pred_risk'),
    sa.CheckConstraint("soh_source IN ('measured','physics_ml','physics_only')", name='ck_pred_source'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pred_vehicle_time', 'soh_predictions', ['vehicle_id', 'predicted_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pred_vehicle_time', table_name='soh_predictions')
    op.drop_table('soh_predictions')
    op.drop_index('uq_ml_models_one_active', table_name='ml_models', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.drop_index(op.f('ix_ml_models_dataset_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_fleet_training_data_dataset_id'), table_name='fleet_training_data')
    op.drop_index('ix_fleet_dataset_vehicle', table_name='fleet_training_data')
    op.drop_table('fleet_training_data')
    op.drop_index('ix_charge_vehicle_time', table_name='charging_history')
    op.drop_table('charging_history')
    op.drop_index('ix_meas_vehicle_time', table_name='battery_measurements')
    op.drop_table('battery_measurements')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('fleet_datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
